name: linux-build-test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Grab source
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install Redis-server
      run: |
        sudo apt update
        sudo apt install redis-server
        sudo systemctl restart redis-server.service
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
      env:
        EXPLORERSERVER: ${{ secrets.EXPLORERSERVER }}
        RPCSERVER: ${{ secrets.RPCSERVER }}
        DBADDR: ${{ secrets.DBADDR }}
        HOTPORTSIZE: ${{ secrets.HOTPORTSIZE }}
        COLDPORTSIZE: ${{ secrets.COLDPORTSIZE }}
    - name: Send coverage
      run: make codacy-coverage-push
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        EXPLORERSERVER: ${{ secrets.EXPLORERSERVER }}
        RPCSERVER: ${{ secrets.RPCSERVER }}
        DBADDR: ${{ secrets.DBADDR }}
